<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAW2Wnjc\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAW2Wnjc/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerAW2Wnjc.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerAW2Wnjc\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerAW2Wnjc\appAppKernelProdContainer([
    'container.build_hash' => 'AW2Wnjc',
    'container.build_id' => '3a851cef',
    'container.build_time' => 1728744074,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAW2Wnjc');
